### ISSUE TITLE
Theme not working on Arch

### ISSUE THREAD

**Issue by rainer2208** [yusacetin/xfwaita#1]
Hi, I was trying to use this theme on Arch and put it in the folder where all my other themes are. 

Yet, it is not listet in Lx Appearance application. 

Any ideas?

**Comment by yusacetin** [comment]
Hi, this is a theme for the XFCE Window Manager (it is not a GTK theme), it is not intended for LXDE.

**Comment by rainer2208** [comment]
Okay, thanks for clarifying ....
